# Generated by Django 3.2.5 on 2021-07-11 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='contract_end',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contract_start',
            field=models.DateField(),
        ),
    ]
