# Generated by Django 3.2.5 on 2021-07-11 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20210711_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='contract_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
