# Generated by Django 3.2.5 on 2021-07-12 08:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_employee_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(1960, 1, 1)),
        ),
    ]
